name: Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_ID=${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_GPT_MODEL_DEPLOYMENT_ID=${{ secrets.AZURE_OPENAI_GPT_MODEL_DEPLOYMENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}" >> $GITHUB_ENV

          echo "AZURE_SEARCH_SERVICE_ENDPOINT=${{ secrets.AZURE_SEARCH_SERVICE_ENDPOINT }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_INDEX=${{ secrets.AZURE_SEARCH_INDEX }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_DATASOURCE=${{ secrets.AZURE_SEARCH_DATASOURCE }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_SKILLSET=${{ secrets.AZURE_SEARCH_SKILLSET }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_INDEXER=${{ secrets.AZURE_SEARCH_INDEXER }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_ADMIN_KEY=${{ secrets.AZURE_SEARCH_ADMIN_KEY }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_SEMANTIC_CONFIG=${{ secrets.AZURE_SEARCH_SEMANTIC_CONFIG }}" >> $GITHUB_ENV

      - name: Run Application (for testing)
        run: python Chatbot.py