name: Build and publish docker container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t studentwhisperer .
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login devopsstudentwhisperer.azurecr.io/ -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t devopsstudentwhisperer.azurecr.io/student-whisperer:latest .
          docker push devopsstudentwhisperer.azurecr.io/student-whisperer
