name: Trigger auto deployment for studentwhisperercontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/studentwhisperercontainer-AutoDeployTrigger-93dea66f-24a6-4380-9613-70dfd6a898c5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.STUDENTWHISPERERCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STUDENTWHISPERERCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STUDENTWHISPERERCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: devopsstudentwhisperer.azurecr.io
          registryUsername: ${{ secrets.STUDENTWHISPERERCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STUDENTWHISPERERCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: studentwhisperercontainer
          resourceGroup: devops-student-portal-app-rg
          imageToBuild: devopsstudentwhisperer.azurecr.io/studentwhisperercontainer:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


